-- ============================================================
-- User Profile Service (v2) - Multi-provider identity federation
-- PostgreSQL 13+
--
-- Boundaries:
--   - Auth/JWT validated externally (gateway)
--   - user_id is generated HERE (stable internal UUID)
--   - provider sub claims mapped via external_identity table
--   - No social features, no ranking, no goals (post-MVP)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS user_profile;
COMMENT ON SCHEMA user_profile IS
    'User profile microservice schema. Stores profile, biometrics, preferences '
        'and identity federation. Auth and JWT validation are handled by the gateway.';

-- ============================================================
-- ENUMs
-- ============================================================

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'user_profile' AND t.typname = 'biological_sex') THEN
            CREATE TYPE user_profile.biological_sex AS ENUM ('male', 'female', 'not_specified');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'user_profile' AND t.typname = 'fitness_level') THEN
            CREATE TYPE user_profile.fitness_level AS ENUM ('beginner', 'intermediate', 'advanced');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'user_profile' AND t.typname = 'weight_unit') THEN
            CREATE TYPE user_profile.weight_unit AS ENUM ('kg', 'lbs');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'user_profile' AND t.typname = 'height_unit') THEN
            CREATE TYPE user_profile.height_unit AS ENUM ('cm', 'in');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'user_profile' AND t.typname = 'theme') THEN
            CREATE TYPE user_profile.theme AS ENUM ('light', 'dark', 'system');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'user_profile' AND t.typname = 'auth_provider') THEN
            CREATE TYPE user_profile.auth_provider AS ENUM (
                'custom',       -- Internal JWT (MVP)
                'keycloak',     -- Keycloak OIDC
                'google',       -- Google OAuth2
                'apple',        -- Apple Sign In
                'facebook'      -- Facebook OAuth2
                );
        END IF;
    END$$;

-- ============================================================
-- Utility: updated_at trigger
-- ============================================================

CREATE OR REPLACE FUNCTION user_profile.tg_set_updated_at()
    RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION user_profile.tg_set_updated_at() IS
    'Sets updated_at to now() on every UPDATE.';

-- ============================================================
-- Table: profile
-- ============================================================
-- user_id is generated by THIS service on first provisioning.
-- It is the stable internal identity used by all other services.
-- External provider IDs are stored in external_identity.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_profile.profile (
                                                    user_id             UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Display
                                                    display_name        VARCHAR(100)    NOT NULL,
                                                    avatar_url          TEXT,

    -- Biometrics
                                                    date_of_birth       DATE,
                                                    biological_sex      user_profile.biological_sex  NOT NULL DEFAULT 'not_specified',
                                                    height              NUMERIC(5, 1),               -- stored in height_unit
                                                    height_unit         user_profile.height_unit     NOT NULL DEFAULT 'cm',

    -- Fitness context (used by AI and workout recommendations)
                                                    fitness_level       user_profile.fitness_level   NOT NULL DEFAULT 'beginner',
                                                    weekly_target       SMALLINT                     NOT NULL DEFAULT 3,  -- sessions/week

    -- Lifecycle
                                                    deleted_at          TIMESTAMPTZ,                 -- soft delete via event from auth service

                                                    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                                    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

                                                    CONSTRAINT chk_display_name_nonempty
                                                        CHECK (LENGTH(TRIM(display_name)) > 0),
                                                    CONSTRAINT chk_height_positive
                                                        CHECK (height IS NULL OR height > 0),
                                                    CONSTRAINT chk_weekly_target_range
                                                        CHECK (weekly_target BETWEEN 1 AND 14)
);

COMMENT ON TABLE  user_profile.profile IS
    'Core user profile. user_id is the stable internal UUID generated at provisioning. '
        'External provider subjects are stored in external_identity.';
COMMENT ON COLUMN user_profile.profile.user_id IS
    'Stable internal UUID. Generated here, used as foreign key by all other services.';
COMMENT ON COLUMN user_profile.profile.height IS
    'Stored in the unit specified by height_unit. Convert at application layer if needed.';
COMMENT ON COLUMN user_profile.profile.weekly_target IS
    'Self-declared training frequency (sessions/week). Used for adherence calculations.';
COMMENT ON COLUMN user_profile.profile.fitness_level IS
    'Self-declared fitness level. Filters exercise difficulty and AI recommendations.';
COMMENT ON COLUMN user_profile.profile.deleted_at IS
    'Soft delete. Set via event when auth service closes the account.';

CREATE TRIGGER trg_profile_set_updated_at
    BEFORE UPDATE ON user_profile.profile
    FOR EACH ROW EXECUTE FUNCTION user_profile.tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_profile_active
    ON user_profile.profile (user_id)
    WHERE deleted_at IS NULL;

-- ============================================================
-- Table: external_identity
-- ============================================================
-- Federation table: maps (provider, provider_user_id) → user_id.
-- One user can have multiple rows (one per linked provider).
-- This is the ONLY table that knows about external provider IDs.
--
-- Hot path: called by gateway on EVERY authenticated request.
-- Index idx_ext_identity_lookup must stay healthy.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_profile.external_identity (
                                                              id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
                                                              user_id             UUID            NOT NULL,
                                                              provider            user_profile.auth_provider  NOT NULL,
                                                              provider_user_id    VARCHAR(255)    NOT NULL,    -- 'sub' claim from provider JWT
                                                              provider_email      VARCHAR(255),               -- informational only, not used as key
                                                              linked_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                                              last_login_at       TIMESTAMPTZ,

                                                              CONSTRAINT uq_external_identity_provider
                                                                  UNIQUE (provider, provider_user_id),
                                                              CONSTRAINT fk_external_identity_user
                                                                  FOREIGN KEY (user_id) REFERENCES user_profile.profile(user_id)
                                                                      ON DELETE CASCADE
);

COMMENT ON TABLE  user_profile.external_identity IS
    'Identity federation: maps external provider subjects to the internal user_id. '
        'One user may have multiple rows (one per linked provider).';
COMMENT ON COLUMN user_profile.external_identity.provider_user_id IS
    'The "sub" claim from the provider JWT. Stable and unique per provider.';
COMMENT ON COLUMN user_profile.external_identity.provider_email IS
    'Email reported by the provider. Stored for reference only — never used as an identifier.';
COMMENT ON COLUMN user_profile.external_identity.last_login_at IS
    'Updated on every successful resolution. Useful for activity auditing.';

-- Lookup: provider + sub → user_id (gateway hot path, every request)
CREATE INDEX IF NOT EXISTS idx_ext_identity_lookup
    ON user_profile.external_identity (provider, provider_user_id);

-- Reverse: list all providers linked to a user
CREATE INDEX IF NOT EXISTS idx_ext_identity_user
    ON user_profile.external_identity (user_id);

-- ============================================================
-- Table: weight_history
-- ============================================================
-- Append-only log. Never UPDATE rows — always INSERT.
-- Current weight = latest row per user_id.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_profile.weight_history (
                                                           id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
                                                           user_id         UUID            NOT NULL,
                                                           weight          NUMERIC(5, 1)   NOT NULL,
                                                           unit            user_profile.weight_unit    NOT NULL DEFAULT 'kg',
                                                           recorded_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                                           note            VARCHAR(255),   -- optional context, e.g. "morning fasted"

                                                           CONSTRAINT chk_weight_positive CHECK (weight > 0),
                                                           CONSTRAINT fk_weight_user
                                                               FOREIGN KEY (user_id) REFERENCES user_profile.profile(user_id)
                                                                   ON DELETE CASCADE
);

COMMENT ON TABLE  user_profile.weight_history IS
    'Append-only weight log. Current weight = latest row per user. Never update rows.';
COMMENT ON COLUMN user_profile.weight_history.recorded_at IS
    'Measurement timestamp as declared by the user (may differ from insert time).';
COMMENT ON COLUMN user_profile.weight_history.note IS
    'Optional free-text context, e.g. "morning fasted", "post-workout".';

CREATE INDEX IF NOT EXISTS idx_weight_history_user_time
    ON user_profile.weight_history (user_id, recorded_at DESC);

-- ============================================================
-- Table: preferences
-- ============================================================
-- One row per user. Upsert on change.
-- notification_settings in JSONB — evolves without migrations.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_profile.preferences (
                                                        user_id                 UUID        PRIMARY KEY,

    -- Locale & display
                                                        locale                  VARCHAR(10) NOT NULL DEFAULT 'en',   -- BCP-47: it, en, es-MX
                                                        timezone                VARCHAR(50) NOT NULL DEFAULT 'UTC',  -- IANA: Europe/Rome
                                                        theme                   user_profile.theme  NOT NULL DEFAULT 'system',

    -- Unit preferences (denormalized for fast read by other services)
                                                        preferred_weight_unit   user_profile.weight_unit    NOT NULL DEFAULT 'kg',
                                                        preferred_height_unit   user_profile.height_unit    NOT NULL DEFAULT 'cm',

    -- Notification settings (JSONB — add channels without schema migrations)
    -- Structure:
    -- {
    --   "push_enabled": true,
    --   "email_enabled": false,
    --   "channels": {
    --     "workout_reminder": { "enabled": true, "time": "08:00" },
    --     "motivational":     { "enabled": true },
    --     "streak_alert":     { "enabled": true },
    --     "coach_message":    { "enabled": true }
    --   }
    -- }
                                                        notification_settings   JSONB       NOT NULL DEFAULT '{
                                                          "push_enabled": true,
                                                          "email_enabled": false,
                                                          "channels": {
                                                            "workout_reminder": {"enabled": true, "time": "08:00"},
                                                            "motivational":     {"enabled": true},
                                                            "streak_alert":     {"enabled": true},
                                                            "coach_message":    {"enabled": true}
                                                          }
                                                        }',

                                                        updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                                                        CONSTRAINT fk_preferences_user
                                                            FOREIGN KEY (user_id) REFERENCES user_profile.profile(user_id)
                                                                ON DELETE CASCADE,
                                                        CONSTRAINT chk_locale_nonempty
                                                            CHECK (LENGTH(TRIM(locale)) > 0),
                                                        CONSTRAINT chk_timezone_nonempty
                                                            CHECK (LENGTH(TRIM(timezone)) > 0)
);

COMMENT ON TABLE  user_profile.preferences IS
    'App preferences. One row per user, upsert on change.';
COMMENT ON COLUMN user_profile.preferences.locale IS
    'BCP-47 language tag. Propagated by gateway as X-Locale header to all services.';
COMMENT ON COLUMN user_profile.preferences.notification_settings IS
    'Flexible JSONB notification config. Add new channels without schema migrations.';
COMMENT ON COLUMN user_profile.preferences.preferred_weight_unit IS
    'Denormalized here so other services can read unit preference without extra joins.';

CREATE TRIGGER trg_preferences_set_updated_at
    BEFORE UPDATE ON user_profile.preferences
    FOR EACH ROW EXECUTE FUNCTION user_profile.tg_set_updated_at();

-- ============================================================
-- View: v_profile_current
-- ============================================================

CREATE OR REPLACE VIEW user_profile.v_profile_current AS
SELECT
    p.user_id,
    p.display_name,
    p.avatar_url,
    p.date_of_birth,
    p.biological_sex,
    p.height,
    p.height_unit,
    p.fitness_level,
    p.weekly_target,
    p.created_at,
    -- Current weight (latest entry via LATERAL)
    w.weight            AS current_weight,
    w.unit              AS current_weight_unit,
    w.recorded_at       AS weight_recorded_at,
    -- Preferences (most-used fields surfaced directly)
    pr.locale,
    pr.timezone,
    pr.theme,
    pr.preferred_weight_unit,
    pr.preferred_height_unit
FROM      user_profile.profile     p
              LEFT JOIN user_profile.preferences pr ON pr.user_id = p.user_id
              LEFT JOIN LATERAL (
    SELECT weight, unit, recorded_at
    FROM   user_profile.weight_history
    WHERE  user_id = p.user_id
    ORDER  BY recorded_at DESC
    LIMIT  1
    ) w ON TRUE
WHERE p.deleted_at IS NULL;

COMMENT ON VIEW user_profile.v_profile_current IS
    'Active profiles with current weight (latest entry) and preferences. '
        'Single-query read for BFF and gateway enrichment calls.';

-- ============================================================
-- Table summary
-- ============================================================
-- user_profile.profile              Core profile + biometrics (user_id generated here)
-- user_profile.external_identity    Federation: (provider, sub) → internal user_id
-- user_profile.weight_history       Append-only weight log
-- user_profile.preferences          Locale, theme, units, notification settings
--
-- NOT in this service (by design):
--   credentials / password hash     → auth service
--   JWT / refresh tokens            → auth service / gateway
--   ranking / streak / badges       → post-MVP
--   social graph (friends)          → post-MVP
--   fitness goals                   → post-MVP
--   coach-client relationship       → coach-be
-- ============================================================