package it.aredegalli.coachly.user.model;

import com.coachly.userprofile.model.enums.BiologicalSex;
import com.coachly.userprofile.model.enums.FitnessLevel;
import com.coachly.userprofile.model.enums.HeightUnit;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLRestriction;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Core user profile entity.
 *
 * <p>user_id is the stable internal UUID generated at provisioning time.
 * It is never sourced from an external auth provider — external subjects
 * are stored in {@link ExternalIdentity}.
 *
 * <p>Soft-deleted rows (deleted_at != null) are filtered out by the
 * {@code @SQLRestriction} annotation and never returned by standard queries.
 */
@Entity
@Table(schema = "user_profile", name = "profile")
@SQLRestriction("deleted_at IS NULL")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Profile {

    /**
     * Stable internal UUID. Generated by this service at provisioning.
     * All other microservices reference this ID via the X-User-Id header.
     */
    @Id
    @Column(name = "user_id", nullable = false, updatable = false)
    private UUID userId;

    // ── Display ──────────────────────────────────────────────

    @Column(name = "display_name", nullable = false, length = 100)
    private String displayName;

    @Column(name = "avatar_url")
    private String avatarUrl;

    // ── Biometrics ───────────────────────────────────────────

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Enumerated(EnumType.STRING)
    @Column(name = "biological_sex", nullable = false, length = 20)
    private BiologicalSex biologicalSex;

    /**
     * Stored in the unit specified by {@link #heightUnit}.
     * Conversion to a different unit is handled at the application layer.
     */
    @Column(name = "height", precision = 5, scale = 1)
    private BigDecimal height;

    @Enumerated(EnumType.STRING)
    @Column(name = "height_unit", nullable = false, length = 10)
    private HeightUnit heightUnit;

    // ── Fitness context ──────────────────────────────────────

    /**
     * Self-declared fitness level. Used to filter exercise difficulty
     * and tune AI recommendations.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "fitness_level", nullable = false, length = 20)
    private FitnessLevel fitnessLevel;

    /**
     * Self-declared training frequency target (sessions per week, 1-14).
     * Used for adherence calculations.
     */
    @Column(name = "weekly_target", nullable = false)
    private Short weeklyTarget;

    // ── Lifecycle ────────────────────────────────────────────

    /**
     * Soft delete timestamp. Set via domain event when the auth service
     * closes the account. Filtered out automatically by @SQLRestriction.
     */
    @Column(name = "deleted_at")
    private OffsetDateTime deletedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // ── Lifecycle hooks ──────────────────────────────────────

    @PrePersist
    protected void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.biologicalSex == null) {
            this.biologicalSex = BiologicalSex.not_specified;
        }
        if (this.heightUnit == null) {
            this.heightUnit = HeightUnit.cm;
        }
        if (this.weeklyTarget == null) {
            this.weeklyTarget = 3;
        }
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}